//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITF_PEDIDOS
    {
        public int ID_PEDIDO { get; set; }
        public string ORDEN_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public Nullable<int> COD_ESTADO { get; set; }
    }
}
