//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITF_CARTERA
    {
        public int ID_CARTERA { get; set; }
        public string NRO_CUENTA { get; set; }
        public string MONEDA { get; set; }
        public Nullable<int> SALDO { get; set; }
        public string TIPO_CUENTA { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
    }
}
