//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITF_RESPUESTAS_SEGURIDAD
    {
        public int ID_RESPUESTA { get; set; }
        public string RESPUESTA { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public Nullable<int> COD_PREGUNTA { get; set; }
    }
}
