//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITF_MATRICULAS
    {
        public int ID_MATRICULA { get; set; }
        public Nullable<int> COD_ARANCEL { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<long> MONTO { get; set; }
    }
}
