//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITF_EVENTOS
    {
        public int ID_EVENTO { get; set; }
        public string TITULO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string DESCRIPCION_DETALLADA { get; set; }
        public string UBICACION { get; set; }
        public string URL_IMAGEN { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<int> COD_USUARIO_CREADOR { get; set; }
        public Nullable<int> VALOR { get; set; }
        public Nullable<System.DateTime> FECHA_SUBIDA { get; set; }
    }
}
