//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITF_BOLETAS
    {
        public int ID_BOLETA { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> COD_PEDIDO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public string MEDIO_PAGO { get; set; }
        public Nullable<int> NUMERO_TARJETA { get; set; }
        public Nullable<int> ORDEN_COMPRA { get; set; }
        public Nullable<int> CODIGO_AUTORIZACION { get; set; }
    }
}
