//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITFEntities : DbContext
    {
        public ITFEntities()
            : base("name=ITFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ITF_ACADEMIAS> ITF_ACADEMIAS { get; set; }
        public virtual DbSet<ITF_AHORRO_REGISTROS> ITF_AHORRO_REGISTROS { get; set; }
        public virtual DbSet<ITF_AHORRO_TIPO_REGISTROS> ITF_AHORRO_TIPO_REGISTROS { get; set; }
        public virtual DbSet<ITF_AHORROS> ITF_AHORROS { get; set; }
        public virtual DbSet<ITF_ARANCELES> ITF_ARANCELES { get; set; }
        public virtual DbSet<ITF_GENEROS> ITF_GENEROS { get; set; }
        public virtual DbSet<ITF_MATRICULAS> ITF_MATRICULAS { get; set; }
        public virtual DbSet<ITF_TIPO_USUARIOS> ITF_TIPO_USUARIOS { get; set; }
        public virtual DbSet<ITF_VENTA> ITF_VENTA { get; set; }
        public virtual DbSet<ITF_VENTA_DETALLE> ITF_VENTA_DETALLE { get; set; }
        public virtual DbSet<ITF_ACADEMIAS_MAESTRO> ITF_ACADEMIAS_MAESTRO { get; set; }
        public virtual DbSet<ITF_PREGUNTAS_SEGURIDAD> ITF_PREGUNTAS_SEGURIDAD { get; set; }
        public virtual DbSet<ITF_RESPUESTAS_SEGURIDAD> ITF_RESPUESTAS_SEGURIDAD { get; set; }
        public virtual DbSet<ITF_USUARIOS> ITF_USUARIOS { get; set; }
        public virtual DbSet<ITF_CATEGORIAS> ITF_CATEGORIAS { get; set; }
        public virtual DbSet<ITF_PRODUCTOS> ITF_PRODUCTOS { get; set; }
        public virtual DbSet<ITF_PROVEEDORES> ITF_PROVEEDORES { get; set; }
        public virtual DbSet<ITF_PEDIDOS> ITF_PEDIDOS { get; set; }
        public virtual DbSet<ITF_PEDIDOS_DETALLE> ITF_PEDIDOS_DETALLE { get; set; }
        public virtual DbSet<ITF_BOLETAS> ITF_BOLETAS { get; set; }
        public virtual DbSet<ITF_PAGOS> ITF_PAGOS { get; set; }
        public virtual DbSet<ITF_CARTERA> ITF_CARTERA { get; set; }
        public virtual DbSet<ITF_CARTERA_MOVIMIENTOS> ITF_CARTERA_MOVIMIENTOS { get; set; }
        public virtual DbSet<ITF_GRADOS> ITF_GRADOS { get; set; }
        public virtual DbSet<ITF_INDICADORES> ITF_INDICADORES { get; set; }
        public virtual DbSet<ITF_EVENTOS> ITF_EVENTOS { get; set; }
        public virtual DbSet<ITF_EVENTOS_INSCRIPCIONES> ITF_EVENTOS_INSCRIPCIONES { get; set; }
        public virtual DbSet<ITF_FORMAS> ITF_FORMAS { get; set; }
        public virtual DbSet<ITF_EXAMEN_REALIZADOS> ITF_EXAMEN_REALIZADOS { get; set; }
    }
}
